// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Skills.Models;
using System;

namespace Skills.Migrations
{
    [DbContext(typeof(SkillsContext))]
    [Migration("20171029203820_ToProcessExtension")]
    partial class ToProcessExtension
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Skills.Models.LinkModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("SkillModelId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("SkillModelId");

                    b.ToTable("LinkModel");
                });

            modelBuilder.Entity("Skills.Models.SkillModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MinutesSpent");

                    b.Property<string>("SkillName");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Skills.Models.LinkModel", b =>
                {
                    b.HasOne("Skills.Models.SkillModel")
                        .WithMany("ToProcess")
                        .HasForeignKey("SkillModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
